---
application:
  name: "moviesuggestor"
  project: "MovieSuggestorBackend"
  organization: "QoveryCommunity"
routers:
- name: "main-moviesuggestor"
  routes:
  - application_name: "moviesuggestor"
    paths:
    - "/*"
